language: c

os:
  - linux
  - osx

# only build master branch and PR's
branches:
  only:
    - master

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - source asdf/asdf.sh
  # workaround: asdf plugin-test assumes master branch
  - cd $TRAVIS_BUILD_DIR && git checkout -b master || echo 'Already on master'

script:
  - asdf plugin-test tilt $TRAVIS_BUILD_DIR "tilt --help"
