name: Main Workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # schedule:
  #   - cron: "0 0 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: tilt --help
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: asdf_plugin_test_0_22_14
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: tilt --help
          version: "0.22.14"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: asdf_plugin_test_0_22_15
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: tilt --help
          version: "0.22.15"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
